/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AtomLink from './AtomLink';
import AttachmentDtoAllOf from './AttachmentDtoAllOf';
import LinkableDto from './LinkableDto';

/**
 * The AttachmentDto model module.
 * @module model/AttachmentDto
 * @version 7.14.0
 */
class AttachmentDto {
    /**
     * @member {String} id
     * @type {String}
     */
    id;
    /**
     * @member {String} name
     * @type {String}
     */
    name;
    /**
     * @member {String} description
     * @type {String}
     */
    description;
    /**
     * @member {String} taskId
     * @type {String}
     */
    taskId;
    /**
     * @member {String} type
     * @type {String}
     */
    type;
    /**
     * @member {String} url
     * @type {String}
     */
    url;
    /**
     * @member {Date} createTime
     * @type {Date}
     */
    createTime;
    /**
     * @member {Date} removalTime
     * @type {Date}
     */
    removalTime;
    /**
     * @member {String} rootProcessInstanceId
     * @type {String}
     */
    rootProcessInstanceId;
    /**
     * @member {Array.<CodegenProperty{openApiType='AtomLink', baseName='links', complexType='AtomLink', getter='getLinks', setter='setLinks', description='null', dataType='AtomLink', datatypeWithEnum='AtomLink', dataFormat='null', name='links', min='null', max='null', defaultValue='null', defaultValueWithParam=' = AtomLink.constructFromObject(data['links']);', baseType='AtomLink', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/AtomLink"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Links', nameInSnakeCase='LINKS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} links
     * @type {Array.<CodegenProperty{openApiType='AtomLink', baseName='links', complexType='AtomLink', getter='getLinks', setter='setLinks', description='null', dataType='AtomLink', datatypeWithEnum='AtomLink', dataFormat='null', name='links', min='null', max='null', defaultValue='null', defaultValueWithParam=' = AtomLink.constructFromObject(data['links']);', baseType='AtomLink', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/AtomLink"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Links', nameInSnakeCase='LINKS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    links;

    /**
     * @member {String} id
     * @type {String}
     */
    #id;
    /**
     * @member {String} name
     * @type {String}
     */
    #name;
    /**
     * @member {String} description
     * @type {String}
     */
    #description;
    /**
     * @member {String} taskId
     * @type {String}
     */
    #taskId;
    /**
     * @member {String} type
     * @type {String}
     */
    #type;
    /**
     * @member {String} url
     * @type {String}
     */
    #url;
    /**
     * @member {Date} createTime
     * @type {Date}
     */
    #createTime;
    /**
     * @member {Date} removalTime
     * @type {Date}
     */
    #removalTime;
    /**
     * @member {String} rootProcessInstanceId
     * @type {String}
     */
    #rootProcessInstanceId;
    /**
     * @member {Array.<CodegenProperty{openApiType='AtomLink', baseName='links', complexType='AtomLink', getter='getLinks', setter='setLinks', description='null', dataType='AtomLink', datatypeWithEnum='AtomLink', dataFormat='null', name='links', min='null', max='null', defaultValue='null', defaultValueWithParam=' = AtomLink.constructFromObject(data['links']);', baseType='AtomLink', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/AtomLink"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Links', nameInSnakeCase='LINKS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} links
     * @type {Array.<CodegenProperty{openApiType='AtomLink', baseName='links', complexType='AtomLink', getter='getLinks', setter='setLinks', description='null', dataType='AtomLink', datatypeWithEnum='AtomLink', dataFormat='null', name='links', min='null', max='null', defaultValue='null', defaultValueWithParam=' = AtomLink.constructFromObject(data['links']);', baseType='AtomLink', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/AtomLink"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Links', nameInSnakeCase='LINKS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    #links;
    

    /**
     * Constructs a new <code>AttachmentDto</code>.
     * @alias module:model/AttachmentDto
     * @implements module:model/AttachmentDtoAllOf
     * @implements module:model/LinkableDto
     */
    constructor() { 
        AttachmentDtoAllOf.initialize(this);LinkableDto.initialize(this);
        AttachmentDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AttachmentDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttachmentDto} obj Optional instance to populate.
     * @return {module:model/AttachmentDto} The populated <code>AttachmentDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttachmentDto();
            AttachmentDtoAllOf.constructFromObject(data, obj);
            LinkableDto.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Date');
            }
            if (data.hasOwnProperty('removalTime')) {
                obj['removalTime'] = ApiClient.convertToType(data['removalTime'], 'Date');
            }
            if (data.hasOwnProperty('rootProcessInstanceId')) {
                obj['rootProcessInstanceId'] = ApiClient.convertToType(data['rootProcessInstanceId'], 'String');
            }
            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [AtomLink]);
            }
        }
        return obj;
    }
}



export default AttachmentDto;

