/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthorizationExceptionDtoAllOf from './AuthorizationExceptionDtoAllOf';
import ExceptionDto from './ExceptionDto';
import MissingAuthorizationDto from './MissingAuthorizationDto';

/**
 * The AuthorizationExceptionDto model module.
 * @module model/AuthorizationExceptionDto
 * @version 7.14.0
 */
class AuthorizationExceptionDto {
    /**
     * @member {String} userId
     * @type {String}
     */
    userId;
    /**
     * @member {Array.<CodegenProperty{openApiType='MissingAuthorizationDto', baseName='missingAuthorizations', complexType='MissingAuthorizationDto', getter='getMissingAuthorizations', setter='setMissingAuthorizations', description='null', dataType='MissingAuthorizationDto', datatypeWithEnum='MissingAuthorizationDto', dataFormat='null', name='missingAuthorizations', min='null', max='null', defaultValue='null', defaultValueWithParam=' = MissingAuthorizationDto.constructFromObject(data['missingAuthorizations']);', baseType='MissingAuthorizationDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/MissingAuthorizationDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='MissingAuthorizations', nameInSnakeCase='MISSING_AUTHORIZATIONS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} missingAuthorizations
     * @type {Array.<CodegenProperty{openApiType='MissingAuthorizationDto', baseName='missingAuthorizations', complexType='MissingAuthorizationDto', getter='getMissingAuthorizations', setter='setMissingAuthorizations', description='null', dataType='MissingAuthorizationDto', datatypeWithEnum='MissingAuthorizationDto', dataFormat='null', name='missingAuthorizations', min='null', max='null', defaultValue='null', defaultValueWithParam=' = MissingAuthorizationDto.constructFromObject(data['missingAuthorizations']);', baseType='MissingAuthorizationDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/MissingAuthorizationDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='MissingAuthorizations', nameInSnakeCase='MISSING_AUTHORIZATIONS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    missingAuthorizations;
    /**
     * @member {String} type
     * @type {String}
     */
    type;
    /**
     * @member {String} message
     * @type {String}
     */
    message;

    /**
     * @member {String} userId
     * @type {String}
     */
    #userId;
    /**
     * @member {Array.<CodegenProperty{openApiType='MissingAuthorizationDto', baseName='missingAuthorizations', complexType='MissingAuthorizationDto', getter='getMissingAuthorizations', setter='setMissingAuthorizations', description='null', dataType='MissingAuthorizationDto', datatypeWithEnum='MissingAuthorizationDto', dataFormat='null', name='missingAuthorizations', min='null', max='null', defaultValue='null', defaultValueWithParam=' = MissingAuthorizationDto.constructFromObject(data['missingAuthorizations']);', baseType='MissingAuthorizationDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/MissingAuthorizationDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='MissingAuthorizations', nameInSnakeCase='MISSING_AUTHORIZATIONS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} missingAuthorizations
     * @type {Array.<CodegenProperty{openApiType='MissingAuthorizationDto', baseName='missingAuthorizations', complexType='MissingAuthorizationDto', getter='getMissingAuthorizations', setter='setMissingAuthorizations', description='null', dataType='MissingAuthorizationDto', datatypeWithEnum='MissingAuthorizationDto', dataFormat='null', name='missingAuthorizations', min='null', max='null', defaultValue='null', defaultValueWithParam=' = MissingAuthorizationDto.constructFromObject(data['missingAuthorizations']);', baseType='MissingAuthorizationDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/MissingAuthorizationDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='MissingAuthorizations', nameInSnakeCase='MISSING_AUTHORIZATIONS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    #missingAuthorizations;
    /**
     * @member {String} type
     * @type {String}
     */
    #type;
    /**
     * @member {String} message
     * @type {String}
     */
    #message;
    

    /**
     * Constructs a new <code>AuthorizationExceptionDto</code>.
     * @alias module:model/AuthorizationExceptionDto
     * @implements module:model/AuthorizationExceptionDtoAllOf
     * @implements module:model/ExceptionDto
     */
    constructor() { 
        AuthorizationExceptionDtoAllOf.initialize(this);ExceptionDto.initialize(this);
        AuthorizationExceptionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthorizationExceptionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthorizationExceptionDto} obj Optional instance to populate.
     * @return {module:model/AuthorizationExceptionDto} The populated <code>AuthorizationExceptionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorizationExceptionDto();
            AuthorizationExceptionDtoAllOf.constructFromObject(data, obj);
            ExceptionDto.constructFromObject(data, obj);

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('missingAuthorizations')) {
                obj['missingAuthorizations'] = ApiClient.convertToType(data['missingAuthorizations'], [MissingAuthorizationDto]);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }
}



export default AuthorizationExceptionDto;

