/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import VariableValueDto from './VariableValueDto';

/**
 * The CorrelationMessageDto model module.
 * @module model/CorrelationMessageDto
 * @version 7.14.0
 */
class CorrelationMessageDto {
    /**
     * @member {String} messageName
     * @type {String}
     */
    messageName;
    /**
     * @member {String} businessKey
     * @type {String}
     */
    businessKey;
    /**
     * @member {String} tenantId
     * @type {String}
     */
    tenantId;
    /**
     * @member {Boolean} withoutTenantId
     * @type {Boolean}
     * @default false
     */
    withoutTenantId = false;
    /**
     * @member {String} processInstanceId
     * @type {String}
     */
    processInstanceId;
    /**
     * @member {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} correlationKeys
     * @type {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    correlationKeys;
    /**
     * @member {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} localCorrelationKeys
     * @type {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    localCorrelationKeys;
    /**
     * @member {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processVariables
     * @type {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processVariables;
    /**
     * @member {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processVariablesLocal
     * @type {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processVariablesLocal;
    /**
     * @member {Boolean} all
     * @type {Boolean}
     * @default false
     */
    all = false;
    /**
     * @member {Boolean} resultEnabled
     * @type {Boolean}
     * @default false
     */
    resultEnabled = false;
    /**
     * @member {Boolean} variablesInResultEnabled
     * @type {Boolean}
     * @default false
     */
    variablesInResultEnabled = false;

    

    /**
     * Constructs a new <code>CorrelationMessageDto</code>.
     * @alias module:model/CorrelationMessageDto
     */
    constructor() { 
        
        CorrelationMessageDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CorrelationMessageDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CorrelationMessageDto} obj Optional instance to populate.
     * @return {module:model/CorrelationMessageDto} The populated <code>CorrelationMessageDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CorrelationMessageDto();

            if (data.hasOwnProperty('messageName')) {
                obj['messageName'] = ApiClient.convertToType(data['messageName'], 'String');
            }
            if (data.hasOwnProperty('businessKey')) {
                obj['businessKey'] = ApiClient.convertToType(data['businessKey'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('withoutTenantId')) {
                obj['withoutTenantId'] = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
            }
            if (data.hasOwnProperty('processInstanceId')) {
                obj['processInstanceId'] = ApiClient.convertToType(data['processInstanceId'], 'String');
            }
            if (data.hasOwnProperty('correlationKeys')) {
                obj['correlationKeys'] = ApiClient.convertToType(data['correlationKeys'], {'String': VariableValueDto});
            }
            if (data.hasOwnProperty('localCorrelationKeys')) {
                obj['localCorrelationKeys'] = ApiClient.convertToType(data['localCorrelationKeys'], {'String': VariableValueDto});
            }
            if (data.hasOwnProperty('processVariables')) {
                obj['processVariables'] = ApiClient.convertToType(data['processVariables'], {'String': VariableValueDto});
            }
            if (data.hasOwnProperty('processVariablesLocal')) {
                obj['processVariablesLocal'] = ApiClient.convertToType(data['processVariablesLocal'], {'String': VariableValueDto});
            }
            if (data.hasOwnProperty('all')) {
                obj['all'] = ApiClient.convertToType(data['all'], 'Boolean');
            }
            if (data.hasOwnProperty('resultEnabled')) {
                obj['resultEnabled'] = ApiClient.convertToType(data['resultEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('variablesInResultEnabled')) {
                obj['variablesInResultEnabled'] = ApiClient.convertToType(data['variablesInResultEnabled'], 'Boolean');
            }
        }
        return obj;
    }
}



export default CorrelationMessageDto;

