/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExternalTaskBpmnErrorAllOf model module.
 * @module model/ExternalTaskBpmnErrorAllOf
 * @version 7.14.0
 */
class ExternalTaskBpmnErrorAllOf {
    /**
     * @member {String} workerId
     * @type {String}
     */
    workerId;

    

    /**
     * Constructs a new <code>ExternalTaskBpmnErrorAllOf</code>.
     * @alias module:model/ExternalTaskBpmnErrorAllOf
     */
    constructor() { 
        
        ExternalTaskBpmnErrorAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExternalTaskBpmnErrorAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExternalTaskBpmnErrorAllOf} obj Optional instance to populate.
     * @return {module:model/ExternalTaskBpmnErrorAllOf} The populated <code>ExternalTaskBpmnErrorAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExternalTaskBpmnErrorAllOf();

            if (data.hasOwnProperty('workerId')) {
                obj['workerId'] = ApiClient.convertToType(data['workerId'], 'String');
            }
        }
        return obj;
    }
}



export default ExternalTaskBpmnErrorAllOf;

