/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FetchExternalTaskTopicDto from './FetchExternalTaskTopicDto';

/**
 * The FetchExternalTasksDto model module.
 * @module model/FetchExternalTasksDto
 * @version 7.14.0
 */
class FetchExternalTasksDto {
    /**
     * @member {String} workerId
     * @type {String}
     */
    workerId;
    /**
     * @member {Number} maxTasks
     * @type {Number}
     */
    maxTasks;
    /**
     * @member {Boolean} usePriority
     * @type {Boolean}
     */
    usePriority;
    /**
     * @member {Number} asyncResponseTimeout
     * @type {Number}
     */
    asyncResponseTimeout;
    /**
     * @member {Array.<CodegenProperty{openApiType='FetchExternalTaskTopicDto', baseName='topics', complexType='FetchExternalTaskTopicDto', getter='getTopics', setter='setTopics', description='null', dataType='FetchExternalTaskTopicDto', datatypeWithEnum='FetchExternalTaskTopicDto', dataFormat='null', name='topics', min='null', max='null', defaultValue='null', defaultValueWithParam=' = FetchExternalTaskTopicDto.constructFromObject(data['topics']);', baseType='FetchExternalTaskTopicDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/FetchExternalTaskTopicDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Topics', nameInSnakeCase='TOPICS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} topics
     * @type {Array.<CodegenProperty{openApiType='FetchExternalTaskTopicDto', baseName='topics', complexType='FetchExternalTaskTopicDto', getter='getTopics', setter='setTopics', description='null', dataType='FetchExternalTaskTopicDto', datatypeWithEnum='FetchExternalTaskTopicDto', dataFormat='null', name='topics', min='null', max='null', defaultValue='null', defaultValueWithParam=' = FetchExternalTaskTopicDto.constructFromObject(data['topics']);', baseType='FetchExternalTaskTopicDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/FetchExternalTaskTopicDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Topics', nameInSnakeCase='TOPICS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    topics;

    

    /**
     * Constructs a new <code>FetchExternalTasksDto</code>.
     * @alias module:model/FetchExternalTasksDto
     * @param workerId {String} **Mandatory.** The id of the worker on which behalf tasks are fetched. The returned tasks are locked for that worker and can only be completed when providing the same worker id.
     * @param maxTasks {Number} **Mandatory.** The maximum number of tasks to return.
     */
    constructor(workerId, maxTasks) { 
        
        FetchExternalTasksDto.initialize(this, workerId, maxTasks);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workerId, maxTasks) { 
        obj['workerId'] = workerId;
        obj['maxTasks'] = maxTasks;
    }

    /**
     * Constructs a <code>FetchExternalTasksDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FetchExternalTasksDto} obj Optional instance to populate.
     * @return {module:model/FetchExternalTasksDto} The populated <code>FetchExternalTasksDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FetchExternalTasksDto();

            if (data.hasOwnProperty('workerId')) {
                obj['workerId'] = ApiClient.convertToType(data['workerId'], 'String');
            }
            if (data.hasOwnProperty('maxTasks')) {
                obj['maxTasks'] = ApiClient.convertToType(data['maxTasks'], 'Number');
            }
            if (data.hasOwnProperty('usePriority')) {
                obj['usePriority'] = ApiClient.convertToType(data['usePriority'], 'Boolean');
            }
            if (data.hasOwnProperty('asyncResponseTimeout')) {
                obj['asyncResponseTimeout'] = ApiClient.convertToType(data['asyncResponseTimeout'], 'Number');
            }
            if (data.hasOwnProperty('topics')) {
                obj['topics'] = ApiClient.convertToType(data['topics'], [FetchExternalTaskTopicDto]);
            }
        }
        return obj;
    }
}



export default FetchExternalTasksDto;

