/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HistoricActivityInstanceDto model module.
 * @module model/HistoricActivityInstanceDto
 * @version 7.14.0
 */
class HistoricActivityInstanceDto {
    /**
     * @member {String} id
     * @type {String}
     */
    id;
    /**
     * @member {String} parentActivityInstanceId
     * @type {String}
     */
    parentActivityInstanceId;
    /**
     * @member {String} activityId
     * @type {String}
     */
    activityId;
    /**
     * @member {String} activityName
     * @type {String}
     */
    activityName;
    /**
     * @member {String} activityType
     * @type {String}
     */
    activityType;
    /**
     * @member {String} processDefinitionKey
     * @type {String}
     */
    processDefinitionKey;
    /**
     * @member {String} processDefinitionId
     * @type {String}
     */
    processDefinitionId;
    /**
     * @member {String} processInstanceId
     * @type {String}
     */
    processInstanceId;
    /**
     * @member {String} executionId
     * @type {String}
     */
    executionId;
    /**
     * @member {String} taskId
     * @type {String}
     */
    taskId;
    /**
     * @member {String} assignee
     * @type {String}
     */
    assignee;
    /**
     * @member {String} calledProcessInstanceId
     * @type {String}
     */
    calledProcessInstanceId;
    /**
     * @member {String} calledCaseInstanceId
     * @type {String}
     */
    calledCaseInstanceId;
    /**
     * @member {Date} startTime
     * @type {Date}
     */
    startTime;
    /**
     * @member {Date} endTime
     * @type {Date}
     */
    endTime;
    /**
     * @member {Number} durationInMillis
     * @type {Number}
     */
    durationInMillis;
    /**
     * @member {Boolean} canceled
     * @type {Boolean}
     */
    canceled;
    /**
     * @member {Boolean} completeScope
     * @type {Boolean}
     */
    completeScope;
    /**
     * @member {String} tenantId
     * @type {String}
     */
    tenantId;
    /**
     * @member {Date} removalTime
     * @type {Date}
     */
    removalTime;
    /**
     * @member {String} rootProcessInstanceId
     * @type {String}
     */
    rootProcessInstanceId;

    

    /**
     * Constructs a new <code>HistoricActivityInstanceDto</code>.
     * @alias module:model/HistoricActivityInstanceDto
     */
    constructor() { 
        
        HistoricActivityInstanceDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HistoricActivityInstanceDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HistoricActivityInstanceDto} obj Optional instance to populate.
     * @return {module:model/HistoricActivityInstanceDto} The populated <code>HistoricActivityInstanceDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HistoricActivityInstanceDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('parentActivityInstanceId')) {
                obj['parentActivityInstanceId'] = ApiClient.convertToType(data['parentActivityInstanceId'], 'String');
            }
            if (data.hasOwnProperty('activityId')) {
                obj['activityId'] = ApiClient.convertToType(data['activityId'], 'String');
            }
            if (data.hasOwnProperty('activityName')) {
                obj['activityName'] = ApiClient.convertToType(data['activityName'], 'String');
            }
            if (data.hasOwnProperty('activityType')) {
                obj['activityType'] = ApiClient.convertToType(data['activityType'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKey')) {
                obj['processDefinitionKey'] = ApiClient.convertToType(data['processDefinitionKey'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionId')) {
                obj['processDefinitionId'] = ApiClient.convertToType(data['processDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('processInstanceId')) {
                obj['processInstanceId'] = ApiClient.convertToType(data['processInstanceId'], 'String');
            }
            if (data.hasOwnProperty('executionId')) {
                obj['executionId'] = ApiClient.convertToType(data['executionId'], 'String');
            }
            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('assignee')) {
                obj['assignee'] = ApiClient.convertToType(data['assignee'], 'String');
            }
            if (data.hasOwnProperty('calledProcessInstanceId')) {
                obj['calledProcessInstanceId'] = ApiClient.convertToType(data['calledProcessInstanceId'], 'String');
            }
            if (data.hasOwnProperty('calledCaseInstanceId')) {
                obj['calledCaseInstanceId'] = ApiClient.convertToType(data['calledCaseInstanceId'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'Date');
            }
            if (data.hasOwnProperty('durationInMillis')) {
                obj['durationInMillis'] = ApiClient.convertToType(data['durationInMillis'], 'Number');
            }
            if (data.hasOwnProperty('canceled')) {
                obj['canceled'] = ApiClient.convertToType(data['canceled'], 'Boolean');
            }
            if (data.hasOwnProperty('completeScope')) {
                obj['completeScope'] = ApiClient.convertToType(data['completeScope'], 'Boolean');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('removalTime')) {
                obj['removalTime'] = ApiClient.convertToType(data['removalTime'], 'Date');
            }
            if (data.hasOwnProperty('rootProcessInstanceId')) {
                obj['rootProcessInstanceId'] = ApiClient.convertToType(data['rootProcessInstanceId'], 'String');
            }
        }
        return obj;
    }
}



export default HistoricActivityInstanceDto;

