/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HistoricActivityInstanceQueryDtoSorting from './HistoricActivityInstanceQueryDtoSorting';

/**
 * The HistoricActivityInstanceQueryDto model module.
 * @module model/HistoricActivityInstanceQueryDto
 * @version 7.14.0
 */
class HistoricActivityInstanceQueryDto {
    /**
     * @member {String} activityInstanceId
     * @type {String}
     */
    activityInstanceId;
    /**
     * @member {String} processInstanceId
     * @type {String}
     */
    processInstanceId;
    /**
     * @member {String} processDefinitionId
     * @type {String}
     */
    processDefinitionId;
    /**
     * @member {String} executionId
     * @type {String}
     */
    executionId;
    /**
     * @member {String} activityId
     * @type {String}
     */
    activityId;
    /**
     * @member {String} activityName
     * @type {String}
     */
    activityName;
    /**
     * @member {String} activityType
     * @type {String}
     */
    activityType;
    /**
     * @member {String} taskAssignee
     * @type {String}
     */
    taskAssignee;
    /**
     * @member {Boolean} finished
     * @type {Boolean}
     */
    finished;
    /**
     * @member {Boolean} unfinished
     * @type {Boolean}
     */
    unfinished;
    /**
     * @member {Boolean} canceled
     * @type {Boolean}
     */
    canceled;
    /**
     * @member {Boolean} completeScope
     * @type {Boolean}
     */
    completeScope;
    /**
     * @member {Date} startedBefore
     * @type {Date}
     */
    startedBefore;
    /**
     * @member {Date} startedAfter
     * @type {Date}
     */
    startedAfter;
    /**
     * @member {Date} finishedBefore
     * @type {Date}
     */
    finishedBefore;
    /**
     * @member {Date} finishedAfter
     * @type {Date}
     */
    finishedAfter;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='tenantIdIn', complexType='null', getter='getTenantIdIn', setter='setTenantIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='tenantIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['tenantIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='TenantIdIn', nameInSnakeCase='TENANT_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} tenantIdIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='tenantIdIn', complexType='null', getter='getTenantIdIn', setter='setTenantIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='tenantIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['tenantIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='TenantIdIn', nameInSnakeCase='TENANT_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    tenantIdIn;
    /**
     * @member {Boolean} withoutTenantId
     * @type {Boolean}
     */
    withoutTenantId;
    /**
     * @member {Array.<CodegenProperty{openApiType='HistoricActivityInstanceQueryDtoSorting', baseName='sorting', complexType='HistoricActivityInstanceQueryDtoSorting', getter='getSorting', setter='setSorting', description='null', dataType='HistoricActivityInstanceQueryDtoSorting', datatypeWithEnum='HistoricActivityInstanceQueryDtoSorting', dataFormat='null', name='sorting', min='null', max='null', defaultValue='null', defaultValueWithParam=' = HistoricActivityInstanceQueryDtoSorting.constructFromObject(data['sorting']);', baseType='HistoricActivityInstanceQueryDtoSorting', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/HistoricActivityInstanceQueryDto_sorting"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Sorting', nameInSnakeCase='SORTING', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} sorting
     * @type {Array.<CodegenProperty{openApiType='HistoricActivityInstanceQueryDtoSorting', baseName='sorting', complexType='HistoricActivityInstanceQueryDtoSorting', getter='getSorting', setter='setSorting', description='null', dataType='HistoricActivityInstanceQueryDtoSorting', datatypeWithEnum='HistoricActivityInstanceQueryDtoSorting', dataFormat='null', name='sorting', min='null', max='null', defaultValue='null', defaultValueWithParam=' = HistoricActivityInstanceQueryDtoSorting.constructFromObject(data['sorting']);', baseType='HistoricActivityInstanceQueryDtoSorting', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/HistoricActivityInstanceQueryDto_sorting"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Sorting', nameInSnakeCase='SORTING', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    sorting;

    

    /**
     * Constructs a new <code>HistoricActivityInstanceQueryDto</code>.
     * A historic activity instance query which defines a group of historic activity instances
     * @alias module:model/HistoricActivityInstanceQueryDto
     */
    constructor() { 
        
        HistoricActivityInstanceQueryDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HistoricActivityInstanceQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HistoricActivityInstanceQueryDto} obj Optional instance to populate.
     * @return {module:model/HistoricActivityInstanceQueryDto} The populated <code>HistoricActivityInstanceQueryDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HistoricActivityInstanceQueryDto();

            if (data.hasOwnProperty('activityInstanceId')) {
                obj['activityInstanceId'] = ApiClient.convertToType(data['activityInstanceId'], 'String');
            }
            if (data.hasOwnProperty('processInstanceId')) {
                obj['processInstanceId'] = ApiClient.convertToType(data['processInstanceId'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionId')) {
                obj['processDefinitionId'] = ApiClient.convertToType(data['processDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('executionId')) {
                obj['executionId'] = ApiClient.convertToType(data['executionId'], 'String');
            }
            if (data.hasOwnProperty('activityId')) {
                obj['activityId'] = ApiClient.convertToType(data['activityId'], 'String');
            }
            if (data.hasOwnProperty('activityName')) {
                obj['activityName'] = ApiClient.convertToType(data['activityName'], 'String');
            }
            if (data.hasOwnProperty('activityType')) {
                obj['activityType'] = ApiClient.convertToType(data['activityType'], 'String');
            }
            if (data.hasOwnProperty('taskAssignee')) {
                obj['taskAssignee'] = ApiClient.convertToType(data['taskAssignee'], 'String');
            }
            if (data.hasOwnProperty('finished')) {
                obj['finished'] = ApiClient.convertToType(data['finished'], 'Boolean');
            }
            if (data.hasOwnProperty('unfinished')) {
                obj['unfinished'] = ApiClient.convertToType(data['unfinished'], 'Boolean');
            }
            if (data.hasOwnProperty('canceled')) {
                obj['canceled'] = ApiClient.convertToType(data['canceled'], 'Boolean');
            }
            if (data.hasOwnProperty('completeScope')) {
                obj['completeScope'] = ApiClient.convertToType(data['completeScope'], 'Boolean');
            }
            if (data.hasOwnProperty('startedBefore')) {
                obj['startedBefore'] = ApiClient.convertToType(data['startedBefore'], 'Date');
            }
            if (data.hasOwnProperty('startedAfter')) {
                obj['startedAfter'] = ApiClient.convertToType(data['startedAfter'], 'Date');
            }
            if (data.hasOwnProperty('finishedBefore')) {
                obj['finishedBefore'] = ApiClient.convertToType(data['finishedBefore'], 'Date');
            }
            if (data.hasOwnProperty('finishedAfter')) {
                obj['finishedAfter'] = ApiClient.convertToType(data['finishedAfter'], 'Date');
            }
            if (data.hasOwnProperty('tenantIdIn')) {
                obj['tenantIdIn'] = ApiClient.convertToType(data['tenantIdIn'], ['String']);
            }
            if (data.hasOwnProperty('withoutTenantId')) {
                obj['withoutTenantId'] = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
            }
            if (data.hasOwnProperty('sorting')) {
                obj['sorting'] = ApiClient.convertToType(data['sorting'], [HistoricActivityInstanceQueryDtoSorting]);
            }
        }
        return obj;
    }
}



export default HistoricActivityInstanceQueryDto;

