/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HistoricProcessInstanceQueryDtoSorting from './HistoricProcessInstanceQueryDtoSorting';
import VariableQueryParameterDto from './VariableQueryParameterDto';

/**
 * The HistoricProcessInstanceQueryDto model module.
 * @module model/HistoricProcessInstanceQueryDto
 * @version 7.14.0
 */
class HistoricProcessInstanceQueryDto {
    /**
     * @member {String} processInstanceId
     * @type {String}
     */
    processInstanceId;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='processInstanceIds', complexType='null', getter='getProcessInstanceIds', setter='setProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessInstanceIds', nameInSnakeCase='PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processInstanceIds
     * @type {Array.<CodegenProperty{openApiType='string', baseName='processInstanceIds', complexType='null', getter='getProcessInstanceIds', setter='setProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessInstanceIds', nameInSnakeCase='PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processInstanceIds;
    /**
     * @member {String} processDefinitionId
     * @type {String}
     */
    processDefinitionId;
    /**
     * @member {String} processDefinitionKey
     * @type {String}
     */
    processDefinitionKey;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyIn', complexType='null', getter='getProcessDefinitionKeyIn', setter='setProcessDefinitionKeyIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processDefinitionKeyIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyIn', complexType='null', getter='getProcessDefinitionKeyIn', setter='setProcessDefinitionKeyIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processDefinitionKeyIn;
    /**
     * @member {String} processDefinitionName
     * @type {String}
     */
    processDefinitionName;
    /**
     * @member {String} processDefinitionNameLike
     * @type {String}
     */
    processDefinitionNameLike;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyNotIn', complexType='null', getter='getProcessDefinitionKeyNotIn', setter='setProcessDefinitionKeyNotIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyNotIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyNotIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyNotIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_NOT_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processDefinitionKeyNotIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyNotIn', complexType='null', getter='getProcessDefinitionKeyNotIn', setter='setProcessDefinitionKeyNotIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyNotIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyNotIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyNotIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_NOT_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processDefinitionKeyNotIn;
    /**
     * @member {String} processInstanceBusinessKey
     * @type {String}
     */
    processInstanceBusinessKey;
    /**
     * @member {String} processInstanceBusinessKeyLike
     * @type {String}
     */
    processInstanceBusinessKeyLike;
    /**
     * @member {Boolean} rootProcessInstances
     * @type {Boolean}
     */
    rootProcessInstances;
    /**
     * @member {Boolean} finished
     * @type {Boolean}
     */
    finished;
    /**
     * @member {Boolean} unfinished
     * @type {Boolean}
     */
    unfinished;
    /**
     * @member {Boolean} withIncidents
     * @type {Boolean}
     */
    withIncidents;
    /**
     * @member {Boolean} withRootIncidents
     * @type {Boolean}
     */
    withRootIncidents;
    /**
     * @member {String} incidentType
     * @type {String}
     */
    incidentType;
    /**
     * @member {HistoricProcessInstanceQueryDto.IncidentStatusEnum} incidentStatus
     * @type {HistoricProcessInstanceQueryDto.IncidentStatusEnum}
     */
    incidentStatus;
    /**
     * @member {String} incidentMessage
     * @type {String}
     */
    incidentMessage;
    /**
     * @member {String} incidentMessageLike
     * @type {String}
     */
    incidentMessageLike;
    /**
     * @member {Date} startedBefore
     * @type {Date}
     */
    startedBefore;
    /**
     * @member {Date} startedAfter
     * @type {Date}
     */
    startedAfter;
    /**
     * @member {Date} finishedBefore
     * @type {Date}
     */
    finishedBefore;
    /**
     * @member {Date} finishedAfter
     * @type {Date}
     */
    finishedAfter;
    /**
     * @member {Date} executedActivityAfter
     * @type {Date}
     */
    executedActivityAfter;
    /**
     * @member {Date} executedActivityBefore
     * @type {Date}
     */
    executedActivityBefore;
    /**
     * @member {Date} executedJobAfter
     * @type {Date}
     */
    executedJobAfter;
    /**
     * @member {Date} executedJobBefore
     * @type {Date}
     */
    executedJobBefore;
    /**
     * @member {String} startedBy
     * @type {String}
     */
    startedBy;
    /**
     * @member {String} superProcessInstanceId
     * @type {String}
     */
    superProcessInstanceId;
    /**
     * @member {String} subProcessInstanceId
     * @type {String}
     */
    subProcessInstanceId;
    /**
     * @member {String} superCaseInstanceId
     * @type {String}
     */
    superCaseInstanceId;
    /**
     * @member {String} subCaseInstanceId
     * @type {String}
     */
    subCaseInstanceId;
    /**
     * @member {String} caseInstanceId
     * @type {String}
     */
    caseInstanceId;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='tenantIdIn', complexType='null', getter='getTenantIdIn', setter='setTenantIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='tenantIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['tenantIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='TenantIdIn', nameInSnakeCase='TENANT_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} tenantIdIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='tenantIdIn', complexType='null', getter='getTenantIdIn', setter='setTenantIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='tenantIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['tenantIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='TenantIdIn', nameInSnakeCase='TENANT_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    tenantIdIn;
    /**
     * @member {Boolean} withoutTenantId
     * @type {Boolean}
     */
    withoutTenantId;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='executedActivityIdIn', complexType='null', getter='getExecutedActivityIdIn', setter='setExecutedActivityIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='executedActivityIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['executedActivityIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ExecutedActivityIdIn', nameInSnakeCase='EXECUTED_ACTIVITY_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} executedActivityIdIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='executedActivityIdIn', complexType='null', getter='getExecutedActivityIdIn', setter='setExecutedActivityIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='executedActivityIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['executedActivityIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ExecutedActivityIdIn', nameInSnakeCase='EXECUTED_ACTIVITY_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    executedActivityIdIn;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='activeActivityIdIn', complexType='null', getter='getActiveActivityIdIn', setter='setActiveActivityIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='activeActivityIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['activeActivityIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ActiveActivityIdIn', nameInSnakeCase='ACTIVE_ACTIVITY_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} activeActivityIdIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='activeActivityIdIn', complexType='null', getter='getActiveActivityIdIn', setter='setActiveActivityIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='activeActivityIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['activeActivityIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ActiveActivityIdIn', nameInSnakeCase='ACTIVE_ACTIVITY_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    activeActivityIdIn;
    /**
     * @member {Boolean} active
     * @type {Boolean}
     */
    active;
    /**
     * @member {Boolean} suspended
     * @type {Boolean}
     */
    suspended;
    /**
     * @member {Boolean} completed
     * @type {Boolean}
     */
    completed;
    /**
     * @member {Boolean} externallyTerminated
     * @type {Boolean}
     */
    externallyTerminated;
    /**
     * @member {Boolean} internallyTerminated
     * @type {Boolean}
     */
    internallyTerminated;
    /**
     * @member {Array.<CodegenProperty{openApiType='VariableQueryParameterDto', baseName='variables', complexType='VariableQueryParameterDto', getter='getVariables', setter='setVariables', description='null', dataType='VariableQueryParameterDto', datatypeWithEnum='VariableQueryParameterDto', dataFormat='null', name='variables', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableQueryParameterDto.constructFromObject(data['variables']);', baseType='VariableQueryParameterDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableQueryParameterDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Variables', nameInSnakeCase='VARIABLES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} variables
     * @type {Array.<CodegenProperty{openApiType='VariableQueryParameterDto', baseName='variables', complexType='VariableQueryParameterDto', getter='getVariables', setter='setVariables', description='null', dataType='VariableQueryParameterDto', datatypeWithEnum='VariableQueryParameterDto', dataFormat='null', name='variables', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableQueryParameterDto.constructFromObject(data['variables']);', baseType='VariableQueryParameterDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableQueryParameterDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Variables', nameInSnakeCase='VARIABLES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    variables;
    /**
     * @member {Boolean} variableNamesIgnoreCase
     * @type {Boolean}
     */
    variableNamesIgnoreCase;
    /**
     * @member {Boolean} variableValuesIgnoreCase
     * @type {Boolean}
     */
    variableValuesIgnoreCase;
    /**
     * @member {Array.<CodegenProperty{openApiType='HistoricProcessInstanceQueryDto', baseName='orQueries', complexType='HistoricProcessInstanceQueryDto', getter='getOrQueries', setter='setOrQueries', description='null', dataType='HistoricProcessInstanceQueryDto', datatypeWithEnum='HistoricProcessInstanceQueryDto', dataFormat='null', name='orQueries', min='null', max='null', defaultValue='null', defaultValueWithParam=' = HistoricProcessInstanceQueryDto.constructFromObject(data['orQueries']);', baseType='HistoricProcessInstanceQueryDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/HistoricProcessInstanceQueryDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='OrQueries', nameInSnakeCase='OR_QUERIES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} orQueries
     * @type {Array.<CodegenProperty{openApiType='HistoricProcessInstanceQueryDto', baseName='orQueries', complexType='HistoricProcessInstanceQueryDto', getter='getOrQueries', setter='setOrQueries', description='null', dataType='HistoricProcessInstanceQueryDto', datatypeWithEnum='HistoricProcessInstanceQueryDto', dataFormat='null', name='orQueries', min='null', max='null', defaultValue='null', defaultValueWithParam=' = HistoricProcessInstanceQueryDto.constructFromObject(data['orQueries']);', baseType='HistoricProcessInstanceQueryDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/HistoricProcessInstanceQueryDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='OrQueries', nameInSnakeCase='OR_QUERIES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    orQueries;
    /**
     * @member {Array.<CodegenProperty{openApiType='HistoricProcessInstanceQueryDtoSorting', baseName='sorting', complexType='HistoricProcessInstanceQueryDtoSorting', getter='getSorting', setter='setSorting', description='null', dataType='HistoricProcessInstanceQueryDtoSorting', datatypeWithEnum='HistoricProcessInstanceQueryDtoSorting', dataFormat='null', name='sorting', min='null', max='null', defaultValue='null', defaultValueWithParam=' = HistoricProcessInstanceQueryDtoSorting.constructFromObject(data['sorting']);', baseType='HistoricProcessInstanceQueryDtoSorting', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/HistoricProcessInstanceQueryDto_sorting"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Sorting', nameInSnakeCase='SORTING', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} sorting
     * @type {Array.<CodegenProperty{openApiType='HistoricProcessInstanceQueryDtoSorting', baseName='sorting', complexType='HistoricProcessInstanceQueryDtoSorting', getter='getSorting', setter='setSorting', description='null', dataType='HistoricProcessInstanceQueryDtoSorting', datatypeWithEnum='HistoricProcessInstanceQueryDtoSorting', dataFormat='null', name='sorting', min='null', max='null', defaultValue='null', defaultValueWithParam=' = HistoricProcessInstanceQueryDtoSorting.constructFromObject(data['sorting']);', baseType='HistoricProcessInstanceQueryDtoSorting', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/HistoricProcessInstanceQueryDto_sorting"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Sorting', nameInSnakeCase='SORTING', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    sorting;

    

    /**
     * Constructs a new <code>HistoricProcessInstanceQueryDto</code>.
     * A historic process instance query which defines a group of historic process instances
     * @alias module:model/HistoricProcessInstanceQueryDto
     */
    constructor() { 
        
        HistoricProcessInstanceQueryDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HistoricProcessInstanceQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HistoricProcessInstanceQueryDto} obj Optional instance to populate.
     * @return {module:model/HistoricProcessInstanceQueryDto} The populated <code>HistoricProcessInstanceQueryDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HistoricProcessInstanceQueryDto();

            if (data.hasOwnProperty('processInstanceId')) {
                obj['processInstanceId'] = ApiClient.convertToType(data['processInstanceId'], 'String');
            }
            if (data.hasOwnProperty('processInstanceIds')) {
                obj['processInstanceIds'] = ApiClient.convertToType(data['processInstanceIds'], ['String']);
            }
            if (data.hasOwnProperty('processDefinitionId')) {
                obj['processDefinitionId'] = ApiClient.convertToType(data['processDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKey')) {
                obj['processDefinitionKey'] = ApiClient.convertToType(data['processDefinitionKey'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKeyIn')) {
                obj['processDefinitionKeyIn'] = ApiClient.convertToType(data['processDefinitionKeyIn'], ['String']);
            }
            if (data.hasOwnProperty('processDefinitionName')) {
                obj['processDefinitionName'] = ApiClient.convertToType(data['processDefinitionName'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionNameLike')) {
                obj['processDefinitionNameLike'] = ApiClient.convertToType(data['processDefinitionNameLike'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKeyNotIn')) {
                obj['processDefinitionKeyNotIn'] = ApiClient.convertToType(data['processDefinitionKeyNotIn'], ['String']);
            }
            if (data.hasOwnProperty('processInstanceBusinessKey')) {
                obj['processInstanceBusinessKey'] = ApiClient.convertToType(data['processInstanceBusinessKey'], 'String');
            }
            if (data.hasOwnProperty('processInstanceBusinessKeyLike')) {
                obj['processInstanceBusinessKeyLike'] = ApiClient.convertToType(data['processInstanceBusinessKeyLike'], 'String');
            }
            if (data.hasOwnProperty('rootProcessInstances')) {
                obj['rootProcessInstances'] = ApiClient.convertToType(data['rootProcessInstances'], 'Boolean');
            }
            if (data.hasOwnProperty('finished')) {
                obj['finished'] = ApiClient.convertToType(data['finished'], 'Boolean');
            }
            if (data.hasOwnProperty('unfinished')) {
                obj['unfinished'] = ApiClient.convertToType(data['unfinished'], 'Boolean');
            }
            if (data.hasOwnProperty('withIncidents')) {
                obj['withIncidents'] = ApiClient.convertToType(data['withIncidents'], 'Boolean');
            }
            if (data.hasOwnProperty('withRootIncidents')) {
                obj['withRootIncidents'] = ApiClient.convertToType(data['withRootIncidents'], 'Boolean');
            }
            if (data.hasOwnProperty('incidentType')) {
                obj['incidentType'] = ApiClient.convertToType(data['incidentType'], 'String');
            }
            if (data.hasOwnProperty('incidentStatus')) {
                obj['incidentStatus'] = ApiClient.convertToType(data['incidentStatus'], 'String');
            }
            if (data.hasOwnProperty('incidentMessage')) {
                obj['incidentMessage'] = ApiClient.convertToType(data['incidentMessage'], 'String');
            }
            if (data.hasOwnProperty('incidentMessageLike')) {
                obj['incidentMessageLike'] = ApiClient.convertToType(data['incidentMessageLike'], 'String');
            }
            if (data.hasOwnProperty('startedBefore')) {
                obj['startedBefore'] = ApiClient.convertToType(data['startedBefore'], 'Date');
            }
            if (data.hasOwnProperty('startedAfter')) {
                obj['startedAfter'] = ApiClient.convertToType(data['startedAfter'], 'Date');
            }
            if (data.hasOwnProperty('finishedBefore')) {
                obj['finishedBefore'] = ApiClient.convertToType(data['finishedBefore'], 'Date');
            }
            if (data.hasOwnProperty('finishedAfter')) {
                obj['finishedAfter'] = ApiClient.convertToType(data['finishedAfter'], 'Date');
            }
            if (data.hasOwnProperty('executedActivityAfter')) {
                obj['executedActivityAfter'] = ApiClient.convertToType(data['executedActivityAfter'], 'Date');
            }
            if (data.hasOwnProperty('executedActivityBefore')) {
                obj['executedActivityBefore'] = ApiClient.convertToType(data['executedActivityBefore'], 'Date');
            }
            if (data.hasOwnProperty('executedJobAfter')) {
                obj['executedJobAfter'] = ApiClient.convertToType(data['executedJobAfter'], 'Date');
            }
            if (data.hasOwnProperty('executedJobBefore')) {
                obj['executedJobBefore'] = ApiClient.convertToType(data['executedJobBefore'], 'Date');
            }
            if (data.hasOwnProperty('startedBy')) {
                obj['startedBy'] = ApiClient.convertToType(data['startedBy'], 'String');
            }
            if (data.hasOwnProperty('superProcessInstanceId')) {
                obj['superProcessInstanceId'] = ApiClient.convertToType(data['superProcessInstanceId'], 'String');
            }
            if (data.hasOwnProperty('subProcessInstanceId')) {
                obj['subProcessInstanceId'] = ApiClient.convertToType(data['subProcessInstanceId'], 'String');
            }
            if (data.hasOwnProperty('superCaseInstanceId')) {
                obj['superCaseInstanceId'] = ApiClient.convertToType(data['superCaseInstanceId'], 'String');
            }
            if (data.hasOwnProperty('subCaseInstanceId')) {
                obj['subCaseInstanceId'] = ApiClient.convertToType(data['subCaseInstanceId'], 'String');
            }
            if (data.hasOwnProperty('caseInstanceId')) {
                obj['caseInstanceId'] = ApiClient.convertToType(data['caseInstanceId'], 'String');
            }
            if (data.hasOwnProperty('tenantIdIn')) {
                obj['tenantIdIn'] = ApiClient.convertToType(data['tenantIdIn'], ['String']);
            }
            if (data.hasOwnProperty('withoutTenantId')) {
                obj['withoutTenantId'] = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
            }
            if (data.hasOwnProperty('executedActivityIdIn')) {
                obj['executedActivityIdIn'] = ApiClient.convertToType(data['executedActivityIdIn'], ['String']);
            }
            if (data.hasOwnProperty('activeActivityIdIn')) {
                obj['activeActivityIdIn'] = ApiClient.convertToType(data['activeActivityIdIn'], ['String']);
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('suspended')) {
                obj['suspended'] = ApiClient.convertToType(data['suspended'], 'Boolean');
            }
            if (data.hasOwnProperty('completed')) {
                obj['completed'] = ApiClient.convertToType(data['completed'], 'Boolean');
            }
            if (data.hasOwnProperty('externallyTerminated')) {
                obj['externallyTerminated'] = ApiClient.convertToType(data['externallyTerminated'], 'Boolean');
            }
            if (data.hasOwnProperty('internallyTerminated')) {
                obj['internallyTerminated'] = ApiClient.convertToType(data['internallyTerminated'], 'Boolean');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], [VariableQueryParameterDto]);
            }
            if (data.hasOwnProperty('variableNamesIgnoreCase')) {
                obj['variableNamesIgnoreCase'] = ApiClient.convertToType(data['variableNamesIgnoreCase'], 'Boolean');
            }
            if (data.hasOwnProperty('variableValuesIgnoreCase')) {
                obj['variableValuesIgnoreCase'] = ApiClient.convertToType(data['variableValuesIgnoreCase'], 'Boolean');
            }
            if (data.hasOwnProperty('orQueries')) {
                obj['orQueries'] = ApiClient.convertToType(data['orQueries'], [HistoricProcessInstanceQueryDto]);
            }
            if (data.hasOwnProperty('sorting')) {
                obj['sorting'] = ApiClient.convertToType(data['sorting'], [HistoricProcessInstanceQueryDtoSorting]);
            }
        }
        return obj;
    }
}


/**
 * Allowed values for the <code>incidentStatus</code> property.
 * @enum {String}
 * @readonly
 */
HistoricProcessInstanceQueryDto['IncidentStatusEnum'] = {

    /**
     * value: "open"
     * @const
     */
    "open": "open",

    /**
     * value: "resolved"
     * @const
     */
    "resolved": "resolved"
};



export default HistoricProcessInstanceQueryDto;

