/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExecutionDto from './ExecutionDto';
import ProcessInstanceDto from './ProcessInstanceDto';
import VariableValueDto from './VariableValueDto';

/**
 * The MessageCorrelationResultWithVariableDto model module.
 * @module model/MessageCorrelationResultWithVariableDto
 * @version 7.14.0
 */
class MessageCorrelationResultWithVariableDto {
    /**
     * @member {MessageCorrelationResultWithVariableDto.ResultTypeEnum} resultType
     * @type {MessageCorrelationResultWithVariableDto.ResultTypeEnum}
     */
    resultType;
    /**
     * @member {ProcessInstanceDto} processInstance
     * @type {ProcessInstanceDto}
     */
    processInstance;
    /**
     * @member {ExecutionDto} execution
     * @type {ExecutionDto}
     */
    execution;
    /**
     * @member {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} variables
     * @type {Object.<String, CodegenProperty{openApiType='VariableValueDto', baseName='inner', complexType='VariableValueDto', getter='getInner', setter='setInner', description='null', dataType='VariableValueDto', datatypeWithEnum='VariableValueDto', dataFormat='null', name='inner', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableValueDto.constructFromObject(data['inner']);', baseType='VariableValueDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableValueDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Inner', nameInSnakeCase='INNER', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    variables;

    

    /**
     * Constructs a new <code>MessageCorrelationResultWithVariableDto</code>.
     * The &#x60;processInstance&#x60; property only has a value if the resultType is set to &#x60;ProcessDefinition&#x60;. The processInstance with the properties as described in the [get single instance](https://docs.camunda.org/manual/7.14/reference/rest/process-instance/get/) method.  The &#x60;execution&#x60; property only has a value if the resultType is set to &#x60;Execution&#x60;. The execution with the properties as described in the [get single execution](https://docs.camunda.org/manual/7.14/reference/rest/execution/get/) method.
     * @alias module:model/MessageCorrelationResultWithVariableDto
     */
    constructor() { 
        
        MessageCorrelationResultWithVariableDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessageCorrelationResultWithVariableDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageCorrelationResultWithVariableDto} obj Optional instance to populate.
     * @return {module:model/MessageCorrelationResultWithVariableDto} The populated <code>MessageCorrelationResultWithVariableDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageCorrelationResultWithVariableDto();

            if (data.hasOwnProperty('resultType')) {
                obj['resultType'] = ApiClient.convertToType(data['resultType'], 'String');
            }
            if (data.hasOwnProperty('processInstance')) {
                obj['processInstance'] = ProcessInstanceDto.constructFromObject(data['processInstance']);
            }
            if (data.hasOwnProperty('execution')) {
                obj['execution'] = ExecutionDto.constructFromObject(data['execution']);
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], {'String': VariableValueDto});
            }
        }
        return obj;
    }
}


/**
 * Allowed values for the <code>resultType</code> property.
 * @enum {String}
 * @readonly
 */
MessageCorrelationResultWithVariableDto['ResultTypeEnum'] = {

    /**
     * value: "Execution"
     * @const
     */
    "Execution": "Execution",

    /**
     * value: "ProcessDefinition"
     * @const
     */
    "ProcessDefinition": "ProcessDefinition"
};



export default MessageCorrelationResultWithVariableDto;

