/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProcessInstanceQueryDtoSorting from './ProcessInstanceQueryDtoSorting';
import VariableQueryParameterDto from './VariableQueryParameterDto';

/**
 * The ProcessInstanceQueryDto model module.
 * @module model/ProcessInstanceQueryDto
 * @version 7.14.0
 */
class ProcessInstanceQueryDto {
    /**
     * @member {String} deploymentId
     * @type {String}
     */
    deploymentId;
    /**
     * @member {String} processDefinitionId
     * @type {String}
     */
    processDefinitionId;
    /**
     * @member {String} processDefinitionKey
     * @type {String}
     */
    processDefinitionKey;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyIn', complexType='null', getter='getProcessDefinitionKeyIn', setter='setProcessDefinitionKeyIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processDefinitionKeyIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyIn', complexType='null', getter='getProcessDefinitionKeyIn', setter='setProcessDefinitionKeyIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processDefinitionKeyIn;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyNotIn', complexType='null', getter='getProcessDefinitionKeyNotIn', setter='setProcessDefinitionKeyNotIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyNotIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyNotIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyNotIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_NOT_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processDefinitionKeyNotIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='processDefinitionKeyNotIn', complexType='null', getter='getProcessDefinitionKeyNotIn', setter='setProcessDefinitionKeyNotIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processDefinitionKeyNotIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processDefinitionKeyNotIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessDefinitionKeyNotIn', nameInSnakeCase='PROCESS_DEFINITION_KEY_NOT_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processDefinitionKeyNotIn;
    /**
     * @member {String} businessKey
     * @type {String}
     */
    businessKey;
    /**
     * @member {String} businessKeyLike
     * @type {String}
     */
    businessKeyLike;
    /**
     * @member {String} caseInstanceId
     * @type {String}
     */
    caseInstanceId;
    /**
     * @member {String} superProcessInstance
     * @type {String}
     */
    superProcessInstance;
    /**
     * @member {String} subProcessInstance
     * @type {String}
     */
    subProcessInstance;
    /**
     * @member {String} superCaseInstance
     * @type {String}
     */
    superCaseInstance;
    /**
     * @member {String} subCaseInstance
     * @type {String}
     */
    subCaseInstance;
    /**
     * @member {Boolean} active
     * @type {Boolean}
     */
    active;
    /**
     * @member {Boolean} suspended
     * @type {Boolean}
     */
    suspended;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='processInstanceIds', complexType='null', getter='getProcessInstanceIds', setter='setProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessInstanceIds', nameInSnakeCase='PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} processInstanceIds
     * @type {Array.<CodegenProperty{openApiType='string', baseName='processInstanceIds', complexType='null', getter='getProcessInstanceIds', setter='setProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='processInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['processInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ProcessInstanceIds', nameInSnakeCase='PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    processInstanceIds;
    /**
     * @member {Boolean} withIncident
     * @type {Boolean}
     */
    withIncident;
    /**
     * @member {String} incidentId
     * @type {String}
     */
    incidentId;
    /**
     * @member {String} incidentType
     * @type {String}
     */
    incidentType;
    /**
     * @member {String} incidentMessage
     * @type {String}
     */
    incidentMessage;
    /**
     * @member {String} incidentMessageLike
     * @type {String}
     */
    incidentMessageLike;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='tenantIdIn', complexType='null', getter='getTenantIdIn', setter='setTenantIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='tenantIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['tenantIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='TenantIdIn', nameInSnakeCase='TENANT_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} tenantIdIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='tenantIdIn', complexType='null', getter='getTenantIdIn', setter='setTenantIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='tenantIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['tenantIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='TenantIdIn', nameInSnakeCase='TENANT_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    tenantIdIn;
    /**
     * @member {Boolean} withoutTenantId
     * @type {Boolean}
     */
    withoutTenantId;
    /**
     * @member {Boolean} processDefinitionWithoutTenantId
     * @type {Boolean}
     */
    processDefinitionWithoutTenantId;
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='activityIdIn', complexType='null', getter='getActivityIdIn', setter='setActivityIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='activityIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['activityIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ActivityIdIn', nameInSnakeCase='ACTIVITY_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} activityIdIn
     * @type {Array.<CodegenProperty{openApiType='string', baseName='activityIdIn', complexType='null', getter='getActivityIdIn', setter='setActivityIdIn', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='activityIdIn', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['activityIdIn'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='ActivityIdIn', nameInSnakeCase='ACTIVITY_ID_IN', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    activityIdIn;
    /**
     * @member {Boolean} rootProcessInstances
     * @type {Boolean}
     */
    rootProcessInstances;
    /**
     * @member {Boolean} leafProcessInstances
     * @type {Boolean}
     */
    leafProcessInstances;
    /**
     * @member {Array.<CodegenProperty{openApiType='VariableQueryParameterDto', baseName='variables', complexType='VariableQueryParameterDto', getter='getVariables', setter='setVariables', description='null', dataType='VariableQueryParameterDto', datatypeWithEnum='VariableQueryParameterDto', dataFormat='null', name='variables', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableQueryParameterDto.constructFromObject(data['variables']);', baseType='VariableQueryParameterDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableQueryParameterDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Variables', nameInSnakeCase='VARIABLES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} variables
     * @type {Array.<CodegenProperty{openApiType='VariableQueryParameterDto', baseName='variables', complexType='VariableQueryParameterDto', getter='getVariables', setter='setVariables', description='null', dataType='VariableQueryParameterDto', datatypeWithEnum='VariableQueryParameterDto', dataFormat='null', name='variables', min='null', max='null', defaultValue='null', defaultValueWithParam=' = VariableQueryParameterDto.constructFromObject(data['variables']);', baseType='VariableQueryParameterDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/VariableQueryParameterDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Variables', nameInSnakeCase='VARIABLES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    variables;
    /**
     * @member {Boolean} variableNamesIgnoreCase
     * @type {Boolean}
     */
    variableNamesIgnoreCase;
    /**
     * @member {Boolean} variableValuesIgnoreCase
     * @type {Boolean}
     */
    variableValuesIgnoreCase;
    /**
     * @member {Array.<CodegenProperty{openApiType='ProcessInstanceQueryDto', baseName='orQueries', complexType='ProcessInstanceQueryDto', getter='getOrQueries', setter='setOrQueries', description='null', dataType='ProcessInstanceQueryDto', datatypeWithEnum='ProcessInstanceQueryDto', dataFormat='null', name='orQueries', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ProcessInstanceQueryDto.constructFromObject(data['orQueries']);', baseType='ProcessInstanceQueryDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/ProcessInstanceQueryDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='OrQueries', nameInSnakeCase='OR_QUERIES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} orQueries
     * @type {Array.<CodegenProperty{openApiType='ProcessInstanceQueryDto', baseName='orQueries', complexType='ProcessInstanceQueryDto', getter='getOrQueries', setter='setOrQueries', description='null', dataType='ProcessInstanceQueryDto', datatypeWithEnum='ProcessInstanceQueryDto', dataFormat='null', name='orQueries', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ProcessInstanceQueryDto.constructFromObject(data['orQueries']);', baseType='ProcessInstanceQueryDto', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/ProcessInstanceQueryDto"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='OrQueries', nameInSnakeCase='OR_QUERIES', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    orQueries;
    /**
     * @member {Array.<CodegenProperty{openApiType='ProcessInstanceQueryDtoSorting', baseName='sorting', complexType='ProcessInstanceQueryDtoSorting', getter='getSorting', setter='setSorting', description='null', dataType='ProcessInstanceQueryDtoSorting', datatypeWithEnum='ProcessInstanceQueryDtoSorting', dataFormat='null', name='sorting', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ProcessInstanceQueryDtoSorting.constructFromObject(data['sorting']);', baseType='ProcessInstanceQueryDtoSorting', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/ProcessInstanceQueryDto_sorting"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Sorting', nameInSnakeCase='SORTING', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} sorting
     * @type {Array.<CodegenProperty{openApiType='ProcessInstanceQueryDtoSorting', baseName='sorting', complexType='ProcessInstanceQueryDtoSorting', getter='getSorting', setter='setSorting', description='null', dataType='ProcessInstanceQueryDtoSorting', datatypeWithEnum='ProcessInstanceQueryDtoSorting', dataFormat='null', name='sorting', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ProcessInstanceQueryDtoSorting.constructFromObject(data['sorting']);', baseType='ProcessInstanceQueryDtoSorting', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "$ref" : "#/components/schemas/ProcessInstanceQueryDto_sorting"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=false, isModel=true, isContainer=false, isString=false, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='Sorting', nameInSnakeCase='SORTING', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    sorting;

    

    /**
     * Constructs a new <code>ProcessInstanceQueryDto</code>.
     * A process instance query which defines a group of process instances
     * @alias module:model/ProcessInstanceQueryDto
     */
    constructor() { 
        
        ProcessInstanceQueryDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessInstanceQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessInstanceQueryDto} obj Optional instance to populate.
     * @return {module:model/ProcessInstanceQueryDto} The populated <code>ProcessInstanceQueryDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessInstanceQueryDto();

            if (data.hasOwnProperty('deploymentId')) {
                obj['deploymentId'] = ApiClient.convertToType(data['deploymentId'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionId')) {
                obj['processDefinitionId'] = ApiClient.convertToType(data['processDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKey')) {
                obj['processDefinitionKey'] = ApiClient.convertToType(data['processDefinitionKey'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKeyIn')) {
                obj['processDefinitionKeyIn'] = ApiClient.convertToType(data['processDefinitionKeyIn'], ['String']);
            }
            if (data.hasOwnProperty('processDefinitionKeyNotIn')) {
                obj['processDefinitionKeyNotIn'] = ApiClient.convertToType(data['processDefinitionKeyNotIn'], ['String']);
            }
            if (data.hasOwnProperty('businessKey')) {
                obj['businessKey'] = ApiClient.convertToType(data['businessKey'], 'String');
            }
            if (data.hasOwnProperty('businessKeyLike')) {
                obj['businessKeyLike'] = ApiClient.convertToType(data['businessKeyLike'], 'String');
            }
            if (data.hasOwnProperty('caseInstanceId')) {
                obj['caseInstanceId'] = ApiClient.convertToType(data['caseInstanceId'], 'String');
            }
            if (data.hasOwnProperty('superProcessInstance')) {
                obj['superProcessInstance'] = ApiClient.convertToType(data['superProcessInstance'], 'String');
            }
            if (data.hasOwnProperty('subProcessInstance')) {
                obj['subProcessInstance'] = ApiClient.convertToType(data['subProcessInstance'], 'String');
            }
            if (data.hasOwnProperty('superCaseInstance')) {
                obj['superCaseInstance'] = ApiClient.convertToType(data['superCaseInstance'], 'String');
            }
            if (data.hasOwnProperty('subCaseInstance')) {
                obj['subCaseInstance'] = ApiClient.convertToType(data['subCaseInstance'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('suspended')) {
                obj['suspended'] = ApiClient.convertToType(data['suspended'], 'Boolean');
            }
            if (data.hasOwnProperty('processInstanceIds')) {
                obj['processInstanceIds'] = ApiClient.convertToType(data['processInstanceIds'], ['String']);
            }
            if (data.hasOwnProperty('withIncident')) {
                obj['withIncident'] = ApiClient.convertToType(data['withIncident'], 'Boolean');
            }
            if (data.hasOwnProperty('incidentId')) {
                obj['incidentId'] = ApiClient.convertToType(data['incidentId'], 'String');
            }
            if (data.hasOwnProperty('incidentType')) {
                obj['incidentType'] = ApiClient.convertToType(data['incidentType'], 'String');
            }
            if (data.hasOwnProperty('incidentMessage')) {
                obj['incidentMessage'] = ApiClient.convertToType(data['incidentMessage'], 'String');
            }
            if (data.hasOwnProperty('incidentMessageLike')) {
                obj['incidentMessageLike'] = ApiClient.convertToType(data['incidentMessageLike'], 'String');
            }
            if (data.hasOwnProperty('tenantIdIn')) {
                obj['tenantIdIn'] = ApiClient.convertToType(data['tenantIdIn'], ['String']);
            }
            if (data.hasOwnProperty('withoutTenantId')) {
                obj['withoutTenantId'] = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
            }
            if (data.hasOwnProperty('processDefinitionWithoutTenantId')) {
                obj['processDefinitionWithoutTenantId'] = ApiClient.convertToType(data['processDefinitionWithoutTenantId'], 'Boolean');
            }
            if (data.hasOwnProperty('activityIdIn')) {
                obj['activityIdIn'] = ApiClient.convertToType(data['activityIdIn'], ['String']);
            }
            if (data.hasOwnProperty('rootProcessInstances')) {
                obj['rootProcessInstances'] = ApiClient.convertToType(data['rootProcessInstances'], 'Boolean');
            }
            if (data.hasOwnProperty('leafProcessInstances')) {
                obj['leafProcessInstances'] = ApiClient.convertToType(data['leafProcessInstances'], 'Boolean');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], [VariableQueryParameterDto]);
            }
            if (data.hasOwnProperty('variableNamesIgnoreCase')) {
                obj['variableNamesIgnoreCase'] = ApiClient.convertToType(data['variableNamesIgnoreCase'], 'Boolean');
            }
            if (data.hasOwnProperty('variableValuesIgnoreCase')) {
                obj['variableValuesIgnoreCase'] = ApiClient.convertToType(data['variableValuesIgnoreCase'], 'Boolean');
            }
            if (data.hasOwnProperty('orQueries')) {
                obj['orQueries'] = ApiClient.convertToType(data['orQueries'], [ProcessInstanceQueryDto]);
            }
            if (data.hasOwnProperty('sorting')) {
                obj['sorting'] = ApiClient.convertToType(data['sorting'], [ProcessInstanceQueryDtoSorting]);
            }
        }
        return obj;
    }
}



export default ProcessInstanceQueryDto;

