/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SchemaLogEntryDto model module.
 * @module model/SchemaLogEntryDto
 * @version 7.14.0
 */
class SchemaLogEntryDto {
    /**
     * @member {String} id
     * @type {String}
     */
    id;
    /**
     * @member {Date} timestamp
     * @type {Date}
     */
    timestamp;
    /**
     * @member {String} version
     * @type {String}
     */
    version;

    

    /**
     * Constructs a new <code>SchemaLogEntryDto</code>.
     * @alias module:model/SchemaLogEntryDto
     */
    constructor() { 
        
        SchemaLogEntryDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SchemaLogEntryDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SchemaLogEntryDto} obj Optional instance to populate.
     * @return {module:model/SchemaLogEntryDto} The populated <code>SchemaLogEntryDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SchemaLogEntryDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }
}



export default SchemaLogEntryDto;

