/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbstractSetRemovalTimeDto from './AbstractSetRemovalTimeDto';
import HistoricProcessInstanceQueryDto from './HistoricProcessInstanceQueryDto';
import SetRemovalTimeToHistoricProcessInstancesDtoAllOf from './SetRemovalTimeToHistoricProcessInstancesDtoAllOf';

/**
 * The SetRemovalTimeToHistoricProcessInstancesDto model module.
 * @module model/SetRemovalTimeToHistoricProcessInstancesDto
 * @version 7.14.0
 */
class SetRemovalTimeToHistoricProcessInstancesDto {
    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='historicProcessInstanceIds', complexType='null', getter='getHistoricProcessInstanceIds', setter='setHistoricProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='historicProcessInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['historicProcessInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='HistoricProcessInstanceIds', nameInSnakeCase='HISTORIC_PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} historicProcessInstanceIds
     * @type {Array.<CodegenProperty{openApiType='string', baseName='historicProcessInstanceIds', complexType='null', getter='getHistoricProcessInstanceIds', setter='setHistoricProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='historicProcessInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['historicProcessInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='HistoricProcessInstanceIds', nameInSnakeCase='HISTORIC_PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    historicProcessInstanceIds;
    /**
     * @member {HistoricProcessInstanceQueryDto} historicProcessInstanceQuery
     * @type {HistoricProcessInstanceQueryDto}
     */
    historicProcessInstanceQuery;
    /**
     * @member {Boolean} hierarchical
     * @type {Boolean}
     */
    hierarchical;
    /**
     * @member {Date} absoluteRemovalTime
     * @type {Date}
     */
    absoluteRemovalTime;
    /**
     * @member {Boolean} clearedRemovalTime
     * @type {Boolean}
     */
    clearedRemovalTime;
    /**
     * @member {Boolean} calculatedRemovalTime
     * @type {Boolean}
     */
    calculatedRemovalTime;

    /**
     * @member {Array.<CodegenProperty{openApiType='string', baseName='historicProcessInstanceIds', complexType='null', getter='getHistoricProcessInstanceIds', setter='setHistoricProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='historicProcessInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['historicProcessInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='HistoricProcessInstanceIds', nameInSnakeCase='HISTORIC_PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>} historicProcessInstanceIds
     * @type {Array.<CodegenProperty{openApiType='string', baseName='historicProcessInstanceIds', complexType='null', getter='getHistoricProcessInstanceIds', setter='setHistoricProcessInstanceIds', description='null', dataType='String', datatypeWithEnum='String', dataFormat='null', name='historicProcessInstanceIds', min='null', max='null', defaultValue='null', defaultValueWithParam=' = ApiClient.convertToType(data['historicProcessInstanceIds'], 'String');', baseType='String', containerType='null', title='null', unescapedDescription='null', maxLength=null, minLength=null, pattern='null', example='null', jsonSchema='{
  "type" : "string"
}', minimum='null', maximum='null', exclusiveMinimum=false, exclusiveMaximum=false, required=false, deprecated=false, hasMoreNonReadOnly=false, isPrimitiveType=true, isModel=false, isContainer=false, isString=true, isNumeric=false, isInteger=false, isLong=false, isNumber=false, isFloat=false, isDouble=false, isDecimal=false, isByteArray=false, isBinary=false, isFile=false, isBoolean=false, isDate=false, isDateTime=false, isUuid=false, isUri=false, isEmail=false, isFreeFormObject=false, isArray=false, isMap=false, isEnum=false, isReadOnly=false, isWriteOnly=false, isNullable=false, isSelfReference=false, isCircularReference=false, isDiscriminator=false, _enum=null, allowableValues=null, items=null, additionalProperties=null, vars=[], requiredVars=[], mostInnerItems=null, vendorExtensions={}, hasValidation=false, isInherited=false, discriminatorValue='null', nameInCamelCase='HistoricProcessInstanceIds', nameInSnakeCase='HISTORIC_PROCESS_INSTANCE_IDS', enumName='null', maxItems=null, minItems=null, maxProperties=null, minProperties=null, uniqueItems=false, multipleOf=null, isXmlAttribute=false, xmlPrefix='null', xmlName='null', xmlNamespace='null', isXmlWrapped=false}>}
     */
    #historicProcessInstanceIds;
    /**
     * @member {HistoricProcessInstanceQueryDto} historicProcessInstanceQuery
     * @type {HistoricProcessInstanceQueryDto}
     */
    #historicProcessInstanceQuery;
    /**
     * @member {Boolean} hierarchical
     * @type {Boolean}
     */
    #hierarchical;
    /**
     * @member {Date} absoluteRemovalTime
     * @type {Date}
     */
    #absoluteRemovalTime;
    /**
     * @member {Boolean} clearedRemovalTime
     * @type {Boolean}
     */
    #clearedRemovalTime;
    /**
     * @member {Boolean} calculatedRemovalTime
     * @type {Boolean}
     */
    #calculatedRemovalTime;
    

    /**
     * Constructs a new <code>SetRemovalTimeToHistoricProcessInstancesDto</code>.
     * @alias module:model/SetRemovalTimeToHistoricProcessInstancesDto
     * @implements module:model/SetRemovalTimeToHistoricProcessInstancesDtoAllOf
     * @implements module:model/AbstractSetRemovalTimeDto
     */
    constructor() { 
        SetRemovalTimeToHistoricProcessInstancesDtoAllOf.initialize(this);AbstractSetRemovalTimeDto.initialize(this);
        SetRemovalTimeToHistoricProcessInstancesDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetRemovalTimeToHistoricProcessInstancesDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetRemovalTimeToHistoricProcessInstancesDto} obj Optional instance to populate.
     * @return {module:model/SetRemovalTimeToHistoricProcessInstancesDto} The populated <code>SetRemovalTimeToHistoricProcessInstancesDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetRemovalTimeToHistoricProcessInstancesDto();
            SetRemovalTimeToHistoricProcessInstancesDtoAllOf.constructFromObject(data, obj);
            AbstractSetRemovalTimeDto.constructFromObject(data, obj);

            if (data.hasOwnProperty('historicProcessInstanceIds')) {
                obj['historicProcessInstanceIds'] = ApiClient.convertToType(data['historicProcessInstanceIds'], ['String']);
            }
            if (data.hasOwnProperty('historicProcessInstanceQuery')) {
                obj['historicProcessInstanceQuery'] = HistoricProcessInstanceQueryDto.constructFromObject(data['historicProcessInstanceQuery']);
            }
            if (data.hasOwnProperty('hierarchical')) {
                obj['hierarchical'] = ApiClient.convertToType(data['hierarchical'], 'Boolean');
            }
            if (data.hasOwnProperty('absoluteRemovalTime')) {
                obj['absoluteRemovalTime'] = ApiClient.convertToType(data['absoluteRemovalTime'], 'Date');
            }
            if (data.hasOwnProperty('clearedRemovalTime')) {
                obj['clearedRemovalTime'] = ApiClient.convertToType(data['clearedRemovalTime'], 'Boolean');
            }
            if (data.hasOwnProperty('calculatedRemovalTime')) {
                obj['calculatedRemovalTime'] = ApiClient.convertToType(data['calculatedRemovalTime'], 'Boolean');
            }
        }
        return obj;
    }
}



export default SetRemovalTimeToHistoricProcessInstancesDto;

