/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */



import ApiClient from "../ApiClient";
import ProcessEngineDto from '../model/ProcessEngineDto';

/**
* Engine service.
* @module api/EngineApi
* @version 7.14.0
*/
export default class EngineApi extends ApiClient {

    /**
    * Constructs a new EngineApi. 
    * @alias module:api/EngineApi
    * @class
    */
    constructor() {
      super();
      this.baseURL = null;
    }


    /**
     * Retrieves the names of all process engines available on your platform. **Note**: You cannot prepend `/engine/{name}` to this method.
     * @return {Promise<Array.<ProcessEngineDto>>}
     */
    async getProcessEngineNames() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ProcessEngineDto];

      return this.callApi(
        '/engine', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }


}
