/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */



import ApiClient from "../ApiClient";
import ExceptionDto from '../model/ExceptionDto';
import TelemetryConfigurationDto from '../model/TelemetryConfigurationDto';

/**
* Telemetry service.
* @module api/TelemetryApi
* @version 7.14.0
*/
export default class TelemetryApi extends ApiClient {

    /**
    * Constructs a new TelemetryApi. 
    * @alias module:api/TelemetryApi
    * @class
    */
    constructor() {
      super();
      this.baseURL = null;
    }


    /**
     * Configure Telemetry
     * Configures whether Camunda receives data collection of the process engine setup and usage.
     * @param {Object} opts Optional parameters
     * @param {TelemetryConfigurationDto} opts.telemetryConfigurationDto 
     * @return {Promise}
     */
    async configureTelemetry(opts) {
      opts = opts || {};
      let postBody = opts['telemetryConfigurationDto'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = null;

      return this.callApi(
        '/telemetry/configuration', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Fetch Telemetry Configuration
     * Fetches Telemetry Configuration.
     * @return {Promise<TelemetryConfigurationDto>}
     */
    async getTelemetryConfiguration() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = TelemetryConfigurationDto;

      return this.callApi(
        '/telemetry/configuration', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }


}
