/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FetchExternalTaskTopicDto', function() {
    it('should create an instance of FetchExternalTaskTopicDto', function() {
      // uncomment below and update the code to test FetchExternalTaskTopicDto
      //var instance = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.FetchExternalTaskTopicDto);
    });

    it('should have the property topicName (base name: "topicName")', function() {
      // uncomment below and update the code to test the property topicName
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property lockDuration (base name: "lockDuration")', function() {
      // uncomment below and update the code to test the property lockDuration
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property variables (base name: "variables")', function() {
      // uncomment below and update the code to test the property variables
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property localVariables (base name: "localVariables")', function() {
      // uncomment below and update the code to test the property localVariables
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property businessKey (base name: "businessKey")', function() {
      // uncomment below and update the code to test the property businessKey
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionId (base name: "processDefinitionId")', function() {
      // uncomment below and update the code to test the property processDefinitionId
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionIdIn (base name: "processDefinitionIdIn")', function() {
      // uncomment below and update the code to test the property processDefinitionIdIn
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionKey (base name: "processDefinitionKey")', function() {
      // uncomment below and update the code to test the property processDefinitionKey
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionKeyIn (base name: "processDefinitionKeyIn")', function() {
      // uncomment below and update the code to test the property processDefinitionKeyIn
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionVersionTag (base name: "processDefinitionVersionTag")', function() {
      // uncomment below and update the code to test the property processDefinitionVersionTag
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property withoutTenantId (base name: "withoutTenantId")', function() {
      // uncomment below and update the code to test the property withoutTenantId
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property tenantIdIn (base name: "tenantIdIn")', function() {
      // uncomment below and update the code to test the property tenantIdIn
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property processVariables (base name: "processVariables")', function() {
      // uncomment below and update the code to test the property processVariables
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property deserializeValues (base name: "deserializeValues")', function() {
      // uncomment below and update the code to test the property deserializeValues
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

    it('should have the property includeExtensionProperties (base name: "includeExtensionProperties")', function() {
      // uncomment below and update the code to test the property includeExtensionProperties
      //var instane = new CamundaBpmRestApi.FetchExternalTaskTopicDto();
      //expect(instance).to.be();
    });

  });

}));
