/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.LockedExternalTaskDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LockedExternalTaskDto', function() {
    it('should create an instance of LockedExternalTaskDto', function() {
      // uncomment below and update the code to test LockedExternalTaskDto
      //var instance = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.LockedExternalTaskDto);
    });

    it('should have the property activityId (base name: "activityId")', function() {
      // uncomment below and update the code to test the property activityId
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property activityInstanceId (base name: "activityInstanceId")', function() {
      // uncomment below and update the code to test the property activityInstanceId
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property errorDetails (base name: "errorDetails")', function() {
      // uncomment below and update the code to test the property errorDetails
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property executionId (base name: "executionId")', function() {
      // uncomment below and update the code to test the property executionId
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property lockExpirationTime (base name: "lockExpirationTime")', function() {
      // uncomment below and update the code to test the property lockExpirationTime
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionId (base name: "processDefinitionId")', function() {
      // uncomment below and update the code to test the property processDefinitionId
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionKey (base name: "processDefinitionKey")', function() {
      // uncomment below and update the code to test the property processDefinitionKey
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionVersionTag (base name: "processDefinitionVersionTag")', function() {
      // uncomment below and update the code to test the property processDefinitionVersionTag
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property processInstanceId (base name: "processInstanceId")', function() {
      // uncomment below and update the code to test the property processInstanceId
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property retries (base name: "retries")', function() {
      // uncomment below and update the code to test the property retries
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property suspended (base name: "suspended")', function() {
      // uncomment below and update the code to test the property suspended
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property workerId (base name: "workerId")', function() {
      // uncomment below and update the code to test the property workerId
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property priority (base name: "priority")', function() {
      // uncomment below and update the code to test the property priority
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property topicName (base name: "topicName")', function() {
      // uncomment below and update the code to test the property topicName
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property businessKey (base name: "businessKey")', function() {
      // uncomment below and update the code to test the property businessKey
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

    it('should have the property variables (base name: "variables")', function() {
      // uncomment below and update the code to test the property variables
      //var instane = new CamundaBpmRestApi.LockedExternalTaskDto();
      //expect(instance).to.be();
    });

  });

}));
